/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRegistration;

import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Hospital.Organization.PatientOrganization;
import Business.Hospital.Organization.ReceptionistOrganization;
import Business.Network.Network;
import Business.Organization.Organization;
import UserInterface.MainJFrame;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Pushkar
 */
public class SelectNetworkForm extends javax.swing.JPanel {

    /**
     * Creates new form SelectNetworkForm
     */
    private ArrayList<Network> networks;
    private JPanel container;
    private MainJFrame main;

    public SelectNetworkForm(JPanel container, ArrayList<Network> networkList, MainJFrame main) {

        initComponents();
        this.main = main;
        this.networks = networkList;
        this.container = container;
        cmbNetwork.removeAllItems();
        cmbNetwork.addItem("select");
        for (Network network : networks) {
            cmbNetwork.addItem(network);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbNetwork = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Select your Network");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 220, 270, 32));

        cmbNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNetworkActionPerformed(evt);
            }
        });
        add(cmbNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 147, 30));

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNetworkActionPerformed

    }//GEN-LAST:event_cmbNetworkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Network network = (Network) cmbNetwork.getSelectedItem();
        Enterprise erp = null;
        Organization org = null;
        Organization rec = null;
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof HospitalEnterprise) {
                erp = enterprise;
                for (Organization organization : erp.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof ReceptionistOrganization) {
                        rec = organization;
                        break;
                    }
                }
                for (Organization organ : erp.getOrganizationDirectory().getOrganizationList()) {
                    if (organ instanceof PatientOrganization) {
                        org = organ;
                        break;
                    }
                }
                break;
            }

        }
        if (erp != null && org != null && rec != null) {
            PatientRegistrationForm prf = new PatientRegistrationForm(container, (HospitalEnterprise) erp, (PatientOrganization) org, main);
            container.add("SelectNetwork", prf);
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        } else {
            jLabel2.setText("Sorry. We are not available in your region.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbNetwork;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
