/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CompoundSupplierRole;

import Business.Drug.Compound;
import Business.Enterprise.DrugManufacturingEnterprise;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Mihir
 */
public class ManageInventoryJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    DrugManufacturingEnterprise drugManufacturingEnterprise;

    RowFilter<TableModel, Object> firstFilter;
    RowFilter<TableModel, Object> secondFilter;
    RowFilter<TableModel, Object> thirdFilter;
    RowFilter<TableModel, Object> fourthFilter;

    /**
     * Creates new form ManageInventoryJPanel
     */
    public ManageInventoryJPanel(JPanel userProcessContainer, DrugManufacturingEnterprise drugManufacturingEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.drugManufacturingEnterprise = drugManufacturingEnterprise;
        populateCompoundCatalog();
    }

    public void populateCompoundCatalog() {
        DefaultTableModel model = (DefaultTableModel) tblCompoundCatalog.getModel();
        model.setRowCount(0);
        for (Compound compound : drugManufacturingEnterprise.getMasterCompoundCatalog().getCompoundList()) {
            Object row[] = new Object[4];
            row[0] = compound.getId();
            row[1] = compound;
            row[2] = compound.getMolecularFormula();
            row[3] = compound.getQuantity();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompoundCatalog = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtQuantity = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtFormula = new javax.swing.JTextField();
        btnClearFilter = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCompoundCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Formula", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCompoundCatalog.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblCompoundCatalog);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 177, 590, 100));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("Compund Catalog");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 49, 157, 30));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 311, 65, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 311, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 311, -1, -1));

        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });
        add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 140, -1));

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdKeyReleased(evt);
            }
        });
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 140, -1));

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 130, -1));

        txtFormula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFormulaKeyReleased(evt);
            }
        });
        add(txtFormula, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 140, -1));

        btnClearFilter.setText("Clear Filter");
        btnClearFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFilterActionPerformed(evt);
            }
        });
        add(btnClearFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        AddCompoundJPanel acjp = new AddCompoundJPanel(userProcessContainer, drugManufacturingEnterprise);
        userProcessContainer.add("AddCompoundJPanel", acjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCompoundCatalog.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table");
            return;
        }
        Compound selectedCompound = (Compound) tblCompoundCatalog.getValueAt(selectedRow, 1);
        UpdateCompoundJPanel ucjp = new UpdateCompoundJPanel(userProcessContainer, drugManufacturingEnterprise, selectedCompound);
        userProcessContainer.add("UpdateCompoundJPanel", ucjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCompoundCatalog.getSelectedRow();
        if (selectedRow >= 0) {
            Compound compound = (Compound) tblCompoundCatalog.getValueAt(selectedRow, tblCompoundCatalog.getColumn("Name").getModelIndex());
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogResult == 0) {
                drugManufacturingEnterprise.getMasterCompoundCatalog().deleteCompound(compound);
                populateCompoundCatalog();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row.", "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFilterActionPerformed
        // TODO add your handling code here:
        txtId.setText("");
        txtName.setText("");
        txtFormula.setText("");
        txtQuantity.setText("");
        firstFilter = RowFilter.regexFilter("", 0);
        secondFilter = RowFilter.regexFilter("", 1);
        thirdFilter = RowFilter.regexFilter("", 2);
        fourthFilter = RowFilter.regexFilter("", 3);
        FilterTable();
    }//GEN-LAST:event_btnClearFilterActionPerformed

    private void txtIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyReleased
        // TODO add your handling code here:
        firstFilter = RowFilter.regexFilter(String.valueOf("(?i)" + txtId.getText().trim()), 0);
        FilterTable();
    }//GEN-LAST:event_txtIdKeyReleased

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        secondFilter = RowFilter.regexFilter(String.valueOf("(?i)" + txtName.getText().trim()), 1);
        FilterTable();
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtFormulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFormulaKeyReleased
        // TODO add your handling code here:
        thirdFilter = RowFilter.regexFilter(String.valueOf("(?i)" + txtFormula.getText().trim()), 2);
        FilterTable();
    }//GEN-LAST:event_txtFormulaKeyReleased

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        // TODO add your handling code here:
        fourthFilter = RowFilter.regexFilter(String.valueOf("(?i)" + txtQuantity.getText().trim()), 3);
        FilterTable();
    }//GEN-LAST:event_txtQuantityKeyReleased

    private void FilterTable() {
        final List<RowFilter<TableModel, Object>> filters = new ArrayList<RowFilter<TableModel, Object>>();
        if (firstFilter != null) {
            filters.add(firstFilter);
        }
        if (secondFilter != null) {
            filters.add(secondFilter);
        }
        if (thirdFilter != null) {
            filters.add(thirdFilter);
        }
        if (fourthFilter != null) {
            filters.add(fourthFilter);
        }
        final RowFilter<TableModel, Object> compoundRowFilter = RowFilter.andFilter(filters);
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<DefaultTableModel>((DefaultTableModel) tblCompoundCatalog.getModel());
        rowSorter.setRowFilter(compoundRowFilter);
        tblCompoundCatalog.setRowSorter(rowSorter);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClearFilter;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCompoundCatalog;
    private javax.swing.JTextField txtFormula;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
