/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DrugManufacturingRole;

import Business.Disease.Disease;
import Business.Drug.Compound;
import Business.Drug.DrugDirectory;
import Business.Drug.DrugVersions;
import Business.Drug.Drugs;
import Business.DrugManufacturing.Organization.DrugManufacturingOrganization;
import Business.DrugManufacturing.Organization.DrugTrialOrganization;
import Business.Enterprise.DrugManufacturingEnterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DrugTrialWorkRequest;
import java.awt.CardLayout;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;

/**
 *
 * @author Mihir
 */
public class CreateDrug extends javax.swing.JPanel {

    /**
     * Creates new form CreateDrug
     */
    JPanel userProcessContainer;
    DrugManufacturingOrganization drugManufacturingOrganization;
    DrugDirectory drugDirectory;
    Disease disease;
    DrugManufacturingEnterprise drugManufacturingEnterprise;
    UserAccount account;
    
    public CreateDrug(JPanel userProcessContainer, UserAccount account, DrugManufacturingOrganization drugManufacturingOrganization, DrugManufacturingEnterprise drugManufacturingEnterprise, Disease disease) {
        initComponents();
        this.disease = disease;
        this.account = account;
        this.drugManufacturingEnterprise = drugManufacturingEnterprise;
        this.drugManufacturingOrganization = drugManufacturingOrganization;
        this.userProcessContainer = userProcessContainer;
        txtDiseaseCured.setText(disease.getName());
        txtFormula.setText("Unavailable");
        populateRouteComboBox();
        populateCompoundList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDrugName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblUses = new javax.swing.JLabel();
        lblRoute = new javax.swing.JLabel();
        lblDiseaseCured = new javax.swing.JLabel();
        txtDrugName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        txtUses = new javax.swing.JTextField();
        txtDiseaseCured = new javax.swing.JTextField();
        txtBenefits = new javax.swing.JTextField();
        txtUses1 = new javax.swing.JTextField();
        lblBenefits = new javax.swing.JLabel();
        lblUses1 = new javax.swing.JLabel();
        lblCompoundUsed = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        cmbRoute = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        ltCompounds = new javax.swing.JList();
        lblFormula = new javax.swing.JLabel();
        txtFormula = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREATE DRUG");

        lblDrugName.setText("Drug Name:");

        lblDescription.setText("Description:");

        lblUses.setText("Uses:");

        lblRoute.setText("Route:");

        lblDiseaseCured.setText("Related Disease");

        txtDiseaseCured.setEnabled(false);

        lblBenefits.setText("Benefits:");

        lblUses1.setText("Formula:");

        lblCompoundUsed.setText("Compound Used:");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        cmbRoute.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRoute.setSelectedIndex(-1);

        jScrollPane1.setViewportView(ltCompounds);

        lblFormula.setText("Formula");

        txtFormula.setEnabled(false);

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblUses)
                                        .addComponent(lblRoute)
                                        .addComponent(lblDrugName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblDiseaseCured)
                                    .addComponent(lblFormula))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFormula, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDrugName, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                            .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                            .addComponent(txtUses, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                            .addComponent(cmbRoute, 0, 145, Short.MAX_VALUE))
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblUses1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCompoundUsed)))
                                    .addComponent(txtDiseaseCured, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUses1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDrugName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBenefits)
                                    .addComponent(txtBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblUses1)
                                    .addComponent(txtUses1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCompoundUsed)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(cmbRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDrugName)
                                .addGap(45, 45, 45)
                                .addComponent(lblDescription)
                                .addGap(36, 36, 36)
                                .addComponent(lblUses)
                                .addGap(38, 38, 38)
                                .addComponent(lblRoute)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFormula)
                                    .addComponent(txtFormula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDiseaseCured)
                                    .addComponent(txtDiseaseCured, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnBack))
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String name = txtDrugName.getText();
        String description = txtDescription.getText();
        String uses = txtUses.getText();
        Drugs.routeType type = (Drugs.routeType) cmbRoute.getSelectedItem();
        String benefits = txtBenefits.getText();
       // String sideEffects = txtSideEffects.getText();
        String vformula = txtUses1.getText();
        Drugs drug = drugManufacturingEnterprise.getDrugDirectory().createDrug(name, description, uses, type, vformula, disease, drugManufacturingEnterprise.getName());
        disease.setDrugAvailable(true);
        DrugVersions drugVersions = drug.getDrugHistory().addDrugVersions("To be tested", benefits, vformula);
        for (Object object : ltCompounds.getSelectedValuesList()) {
            Compound c = (Compound) object;
            drugVersions.getCompoundsUsed().getCompoundsUsedList().add(c);
           drugManufacturingOrganization.getProcuredCompoundList().remove(c);
        }
        
        initiateRequest(drug, drugVersions, disease, account);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox cmbRoute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBenefits;
    private javax.swing.JLabel lblCompoundUsed;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDiseaseCured;
    private javax.swing.JLabel lblDrugName;
    private javax.swing.JLabel lblFormula;
    private javax.swing.JLabel lblRoute;
    private javax.swing.JLabel lblUses;
    private javax.swing.JLabel lblUses1;
    private javax.swing.JList ltCompounds;
    private javax.swing.JTextField txtBenefits;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtDiseaseCured;
    private javax.swing.JTextField txtDrugName;
    private javax.swing.JTextField txtFormula;
    private javax.swing.JTextField txtUses;
    private javax.swing.JTextField txtUses1;
    // End of variables declaration//GEN-END:variables

    private void populateRouteComboBox() {
        cmbRoute.removeAllItems();
        
        for (Object obj : Drugs.routeType.values()) {
            cmbRoute.addItem(obj);
        }
    }
    
    private void populateCompoundList() {
        DefaultListModel dlm = new DefaultListModel();
        dlm.clear();
        
        for (Compound compound : drugManufacturingOrganization.getProcuredCompoundList()) {
            dlm.addElement(compound);
            ltCompounds.setModel(dlm);
        }
    }
    
    private void initiateRequest(Drugs drug, DrugVersions drugVersions, Disease disease, UserAccount account) {
        DrugTrialWorkRequest request = new DrugTrialWorkRequest();
        request.setDisease(disease);
        request.setDrug(drug);
        request.setDrugVersions(drugVersions);
        request.setSender(account);
        request.setStatus("Sent");
        request.setResult("Drug sent for testing.");
        
        Organization org = null;
        for (Organization organization : drugManufacturingEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof DrugTrialOrganization) {
                org = organization;
                break;
            }            
        }
        
        ((DrugTrialOrganization) org).getWorkQueue().getWorkRequestList().add(request);
        account.getWorkQueue().getWorkRequestList().add(request);
    }
}
