/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DrugManufacturingRole;

import Business.Disease.DiseaseDirectory;
import Business.DrugManufacturing.Organization.DrugManufacturingOrganization;
import Business.Enterprise.DrugManufacturingEnterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Mihir
 */
public class DrugManufacturingWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugManufacturingWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    DrugManufacturingOrganization drugManufacturingOrganization;
    DrugManufacturingEnterprise drugManufacturingEnterprise;
    DiseaseDirectory diseaseDirectory;

    public DrugManufacturingWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DrugManufacturingOrganization drugManufacturingOrganization, DrugManufacturingEnterprise drugManufacturingEnterprise, DiseaseDirectory diseaseDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.drugManufacturingEnterprise = drugManufacturingEnterprise;
        this.drugManufacturingOrganization = drugManufacturingOrganization;
        this.diseaseDirectory = diseaseDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnProcure = new javax.swing.JButton();
        btnManageDrugs = new javax.swing.JButton();

        lblTitle.setText("DRUG MANUFACTURING WORK AREA");

        btnProcure.setText("Procure Chemical Compounds");
        btnProcure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcureActionPerformed(evt);
            }
        });

        btnManageDrugs.setText("Manage Drugs");
        btnManageDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDrugsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnProcure)
                        .addGap(33, 33, 33)
                        .addComponent(btnManageDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcure)
                    .addComponent(btnManageDrugs))
                .addGap(377, 377, 377))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDrugsActionPerformed
        ManageDrug md = new ManageDrug(userProcessContainer,account, drugManufacturingOrganization, drugManufacturingEnterprise, diseaseDirectory);
        userProcessContainer.add("ManageDrugManufacturingOrganizations", md);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDrugsActionPerformed

    private void btnProcureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcureActionPerformed
        ProcureCompounds pc = new ProcureCompounds(userProcessContainer, drugManufacturingOrganization, drugManufacturingEnterprise,account);
        userProcessContainer.add("ProcureCompounds", pc);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProcureActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageDrugs;
    private javax.swing.JButton btnProcure;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
