/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DrugEvaluationRole;

import Business.Disease.DiseaseDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FDAEnterprise;
import Business.FDA.Organization.DrugEvaluationOrganization;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author Pushkar
 */
public class DrugEvaluationWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugEvaluationWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    DrugEvaluationOrganization drugEvaluationOrganization;
    FDAEnterprise fdaEnterprise;
    DiseaseDirectory diseaseDirectory;
    Network network;

    public DrugEvaluationWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DrugEvaluationOrganization drugEvaluationOrganization, FDAEnterprise fdaEnterprise, DiseaseDirectory diseaseDirectory, Network network) {
        initComponents();
      this.userProcessContainer= userProcessContainer;
      this.account = account;
      this.drugEvaluationOrganization= drugEvaluationOrganization;
      this.fdaEnterprise = fdaEnterprise;
      this.diseaseDirectory= diseaseDirectory;
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
